name: Tests

on:
  push:
    paths-ignore:
      - 'readme.md'
      - 'assets/**'
  pull_request:
    paths-ignore:
      - 'readme.md'
      - 'assets/**'
  release:

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        laravel: [11.*]
        php: [8.3]

    name: Laravel ${{ matrix.laravel }}, PHP ${{ matrix.php }}

    services:
      mongodb:
        image: bitnami/mongodb:latest
        ports:
          - 27017:27017
        options: > 
          -e MONGODB_REPLICA_SET_MODE=primary 
          -e MONGODB_REPLICA_SET_NAME=rs0 
          -e MONGODB_PORT_NUMBER=27017 
          -e MONGODB_ROOT_PASSWORD=rootpassword

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, bcmath, soap, intl, gd, exif, iconv, imagick, mongodb

      - name: Wait for MongoDB to start
        run: sleep 20

      - name: Install dependencies
        run: |
            composer require --dev "illuminate/auth:${{ matrix.laravel }}" "illuminate/cache:${{ matrix.laravel }}" "illuminate/container:${{ matrix.laravel }}" "illuminate/contracts:${{ matrix.laravel }}" "illuminate/database:${{ matrix.laravel }}" "illuminate/console:${{ matrix.laravel }}" "illuminate/events:${{ matrix.laravel }}" --no-interaction --no-update
            composer update --prefer-stable --prefer-dist --no-interaction --no-suggest

      - name: Set up environment for MongoDB
        run: |
          cp .env.example .env
          php artisan key:generate
          echo "DB_CONNECTION=mongodb" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=27017" >> .env
          echo "DB_DATABASE=your_database_name" >> .env
          echo "DB_USERNAME=root" >> .env
          echo "DB_PASSWORD=rootpassword" >> .env
          echo "DB_OPTIONS=replicaSet=rs0" >> .env

      - name: Run tests
        run: vendor/bin/pest --do-not-cache-result
